# Generated by Django 4.2.1 on 2023-05-21 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(max_length=100)),
                ('cost', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('gst_number', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('gst_number', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(max_length=100)),
                ('bill_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
