# Generated by Django 4.2.1 on 2023-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_inventory_cost_alter_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
